name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'  # 你可以指定需要的 pnpm 版本

      - name: Install dependencies
        run: pnpm install  # 使用 pnpm 安装依赖

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8'  # 确保部署时使用相同版本的 pnpm

      - name: Build project
        run: |
          pnpm install  # 使用 pnpm 安装依赖
          pnpm run build  # 使用 pnpm 构建项目

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist  # 输出目录
          keep_files: true  # 保留历史文件
